- packages/types/src/index.test.ts
- packages/types/src/index.ts
My first step to making aliased types actually infer the proper type.
https://sanity-io-land.slack.com/archives/CT03N628J/p1686685266785399?thread_ts=1686618799.606549&cid=CT03N628J
> Aliased Types infer unknown

- packages/types/src/index.test.ts
- packages/types/src/index.ts
> fix(object): inferring objects from config works

- packages/types/src/index.test.ts
- packages/types/src/index.ts
> fix(objects): objects in defineType derive with _type

- README.md
- packages/schema-builder/README.md
- packages/schema-builder/package.json
- packages/types/README.md
BREAKING CHANGE: Deprecating schema-builder
> fix(schema-builder): deprecating schema-builder

- .github/settings.yml
- README.md
- package-lock.json
- packages/groq/LICENSE
- packages/groq/README.md
- packages/groq/package.json
- packages/groq/src/index.test.ts
- packages/groq/src/index.ts
- packages/groq/src/utils.ts
- packages/groq/tsconfig.json
- packages/types/src/index.ts
My first attempt at typing the GROQ language's output. We'll likely also want to type the sanity client's output but, for now, I'm starting with typing a groq string's output. I'm mostly just using the GROQ spec to try and get the CFG correct, so we'll see how that goes. This is very much an alpha version, not sure how to properly convey that as we move forward. Maybe in an alpha branch?
> Starting the GROQ Project

- packages/types/src/index.test.ts
- packages/types/src/index.ts
> fix(config): coerce defineConfig return type to include/exclude array

- packages/types/README.md
- packages/types/src/aliased-type.test.ts
- packages/types/src/index.ts
- packages/types/src/interoperability.test.ts
> feat(types): castToTyped and castFromTyped for interoperability

- packages/test-utils/src/index.ts
- packages/types/src/block.test.ts
- packages/types/src/index.ts
> fix(block): block types can have children other than spans

- packages/groq/src/data-types.test.ts
- packages/groq/src/index.ts
- packages/groq/src/whitespace.test.ts
> feat(groq): allow whitespace in groqs

- package-lock.json
- packages/groq/package.json
- packages/groq/src/functions.test.ts
- packages/groq/src/index.ts
> feat(geo): global::geo

- packages/client/src/index.test.ts
- packages/client/src/index.ts
- packages/groq/src/functions.test.ts
- packages/groq/src/index.ts
- packages/groq/src/operators.test.ts
- packages/groq/src/simple-expressions.test.ts
- packages/groq/src/traversal-operators.test.ts
> feat(params): params in groq queries

- .eslintrc
- packages/groq-js/src/evaluate.test.ts
- packages/groq/src/data-types.test.ts
- packages/groq/src/functions.test.ts
- packages/groq/src/index.ts
- packages/groq/src/traversal-operators.test.ts
- packages/test-utils/src/index.test.ts
- packages/types/src/document.test.ts
- packages/types/src/index.ts
Use TODO instead. FIXME should be used to block a merge
> disallow FIXME

- packages/groq/src/index.ts
- packages/groq/src/precedence-and-associativity.test.ts
> fix(groq): a bunch of precedence and associativity tests

- packages/groq/src/compound-expressions.test.ts
- packages/groq/src/index.ts
- packages/groq/src/precedence-and-associativity.test.ts
- packages/groq/src/traversal-operators.test.ts
> fix(groq): precedence for compound expressions

- packages/client/src/index.ts
- packages/groq-js/src/evaluate.test.ts
- packages/groq-js/src/index.ts
- packages/groq/src/functions.test.ts
- packages/groq/src/index.ts
> feat(groq): identity()

- packages/groq-js/src/evaluate.test.ts
- packages/groq/src/functions.test.ts
- packages/groq/src/index.ts
https://github.com/sanity-io/groq-js/issues/140
https://github.com/sanity-io/GROQ/issues/111
https://github.com/sanity-io/GROQ/pull/114
> fix(functions): operation is in the delta namespace

- packages/client/README.md
- packages/client/_README.md
- packages/client/docs/cast-to-typed.md
- packages/client/src/index.ts
- packages/client/src/interoperability.test.ts
- packages/types/src/index.ts
> fix(client): castToTyped and castFromTyped

- .github/workflows/checks.yml
- .github/workflows/release.yml
- .husky/pre-commit
- .husky/pre-push
- lint-staged.config.js
- package.json
> fix linting

- packages/types/src/index.ts
- packages/zod/src/index.ts
- packages/zod/src/string.test.ts
- packages/zod/src/text.test.ts
> feat(zod): validate regex from string validations in zod schemas

- packages/zod/src/index.ts
- packages/zod/src/url.test.ts
> feat(zod): validate uri from url validations in zod schemas

- packages/zod/README.md
- packages/zod/_README.md
- packages/zod/src/index.ts
> fix(docs): docs for zod explaining exclusion of custom

- .eslintrc
- package-lock.json
- packages/client/package.json
- packages/faker/package.json
- packages/groq-js/package.json
- packages/groq/package.json
- packages/types/package.json
- packages/zod/package.json
> fix(build): bundle (and unbundle) correct packages

- package-lock.json
- packages/faker/src/validation.test.ts
- packages/traverse-validation/package.json
- packages/traverse-validation/src/index.ts
- packages/types/src/internal.ts
- packages/types/src/validation.test.ts
- packages/zod/src/validation.test.ts
> fix(types): respect Rule.warning()

- .eslintrc
- packages/zod/README.md
- packages/zod/_README.md
- packages/zod/src/array.test.ts
- packages/zod/src/block.test.ts
- packages/zod/src/boolean.test.ts
- packages/zod/src/cross-dataset-reference.test.ts
- packages/zod/src/date.test.ts
- packages/zod/src/datetime.test.ts
- packages/zod/src/document.test.ts
- packages/zod/src/email.test.ts
- packages/zod/src/file.test.ts
- packages/zod/src/geopoint.test.ts
- packages/zod/src/image.test.ts
- packages/zod/src/index.ts
- packages/zod/src/internal.ts
- packages/zod/src/number.test.ts
- packages/zod/src/object.test.ts
- packages/zod/src/reference.test.ts
- packages/zod/src/slug.test.ts
- packages/zod/src/string.test.ts
- packages/zod/src/text.test.ts
- packages/zod/src/url.test.ts
> feat(zod): enableZod includes custom validations in zod validations

- packages/faker/README.md
- packages/faker/_README.md
- packages/faker/src/array.test.ts
- packages/faker/src/block.test.ts
- packages/faker/src/boolean.test.ts
- packages/faker/src/cross-dataset-reference.test.ts
- packages/faker/src/date.test.ts
- packages/faker/src/datetime.test.ts
- packages/faker/src/document.test.ts
- packages/faker/src/email.test.ts
- packages/faker/src/file.test.ts
- packages/faker/src/geopoint.test.ts
- packages/faker/src/image.test.ts
- packages/faker/src/index.ts
- packages/faker/src/internal.ts
- packages/faker/src/number.test.ts
- packages/faker/src/object.test.ts
- packages/faker/src/reference.test.ts
- packages/faker/src/slug.test.ts
- packages/faker/src/string.test.ts
- packages/faker/src/text.test.ts
- packages/faker/src/url.test.ts
- packages/zod/src/internal.ts
> feat(faker): customFaker for custom zods

- packages/groq/src/internal.ts
- packages/types/src/index.ts
- packages/types/src/internal.ts
- packages/zod/src/internal.ts
> fix(types): export referenced publicly

- packages/types/src/internal.ts
> fix(types): rule.warning with correct parameters

- packages/groq/README.md
- packages/groq/_README.md
> fix(docs): more complete docs for groq

- packages/client-mock/package.json
- packages/client/package.json
- packages/client/src/index.ts
- packages/faker/package.json
- packages/groq-js/package.json
- packages/groq/package.json
- packages/types/package.json
- packages/zod/package.json
- tsup.config.ts
> changing up dev command slightly

- packages/groq/src/functions.test.ts
- packages/groq/src/internal.ts
> feat(groq): path operator

- packages/faker/src/array.test.ts
- packages/faker/src/date.test.ts
- packages/faker/src/datetime.test.ts
- packages/faker/src/internal.ts
- packages/faker/src/number.test.ts
- packages/faker/src/string.test.ts
- packages/faker/src/text.test.ts
- packages/traverse-validation/src/index.ts
- packages/zod/src/array.test.ts
- packages/zod/src/date.test.ts
- packages/zod/src/datetime.test.ts
- packages/zod/src/internal.ts
- packages/zod/src/number.test.ts
- packages/zod/src/string.test.ts
- packages/zod/src/text.test.ts
> fix(validation): ignore Rule.valueOfField()

- packages/groq/src/internal.ts
- packages/groq/src/precedence-and-associativity.test.ts
> consolidate range logic

- packages/groq/src/functions.test.ts
- packages/groq/src/internal.ts
- packages/groq/src/precedence-and-associativity.test.ts
> feat(groq): select function and pair

- packages/groq/src/internal.ts
- packages/groq/src/operators.test.ts
- packages/groq/src/precedence-and-associativity.test.ts
> fix(groq): match operator

- packages/faker/src/internal.ts
- packages/faker/src/reference.test.ts
- packages/traverse-validation/src/index.ts
- packages/types/src/block.test.ts
- packages/types/src/internal.ts
- packages/types/src/reference.test.ts
- packages/zod/src/internal.ts
- packages/zod/src/reference.test.ts
> feat(reference): _weak & _strengthenOnPublish is inferred from config

- packages/faker/src/internal.ts
> fix(block): instantiate fakers up front

- packages/faker/src/internal.ts
- packages/pt-types/src/internal.ts
- packages/zod/src/internal.ts
> removing comments about #536

- package-lock.json
- package.json
This reverts commit 7f0d5deddde4d3aa50bba1996a5937f275dd8aa9.
> Revert "bump(deps): bump to typescript 5.3.3"

- .github/workflows/checks.yml
- package-lock.json
- packages/client-mock/package.json
- packages/client/package.json
- packages/example-app/package.json
- packages/example-studio/package.json
- packages/faker/package.json
- packages/groq-js/package.json
- packages/groq/package.json
- packages/next-sanity/package.json
- packages/preview-kit/package.json
- packages/pt-types/package.json
- packages/react/package.json
- packages/to-html/package.json
- packages/types/package.json
- packages/zod/package.json
> fix(deps): add peerDependencies for typescript and add ci tests

- docs/considerations/type-instantiation-is-excessively-deep-and-possibly-infinite-query.md
- packages/client-mock/README.md
- packages/client-mock/_README.md
- packages/client/README.md
- packages/client/_README.md
- packages/groq-js/README.md
- packages/groq-js/_README.md
- packages/groq/README.md
- packages/groq/_README.md
- packages/next-sanity/README.md
- packages/next-sanity/_README.md
- packages/preview-kit/README.md
- packages/preview-kit/_README.md
> fix(docs): update docs for complex GROQ queries

- .vscode/extensions.json
- docs/considerations/type-instantiation-is-excessively-deep-and-possibly-infinite-query.md
- docs/considerations/typescript-errors-in-ides.md
- packages/client-mock/README.md
- packages/client-mock/_README.md
- packages/client/README.md
- packages/client/_README.md
- packages/faker/README.md
- packages/faker/_README.md
- packages/groq-js/README.md
- packages/groq-js/_README.md
- packages/groq/README.md
- packages/groq/_README.md
- packages/next-sanity/README.md
- packages/next-sanity/_README.md
- packages/preview-kit/README.md
- packages/preview-kit/_README.md
- packages/types/README.md
- packages/types/_README.md
- packages/zod/README.md
- packages/zod/_README.md
> fix(docs): section for typescript in vscode

- packages/types/src/internal.ts
> fix(types): remove length requirement for fields

- packages/types/src/aliased-type.test.ts
- packages/types/src/internal.ts
> fix(types): aliased types can have group and fieldset

- packages/types/src/internal.ts
> fix(types): use array instead of tuple for ArrayDefinition 'of'
